### ISSUE TITLE
Smart Actions access object

### ISSUE THREAD

**Issue by lucasgerard** [ForestAdmin/forest-rails#232]
## Expected behavior

`object` should be recognized in `Actions`, as it is the case with `Fields`. This would let setting `defaultValue` to the `object` current value for exemple.

## Actual behavior

`object` is not recognized.

## Failure Logs

`action 'Set Permissions', fields: [
    {
      field: 'Dashboard Send Newsletter',
      type: 'Boolean',
      description: "Permission to send newsletters from the Dashboard.",
      defaultValue: "#{ object.permission?(:newsletter) }"
    }]`

returns
![screen shot 2018-01-30 at 15 06 35](https://user-images.githubusercontent.com/5589858/35570458-9194f8c2-05cf-11e8-8d72-850354769a55.png)

## Context

Package Version: forest_liana (2.0.4)
Rails Version: rails (4.2.10)
Database Version: PG Version 9.6.6

**Comment by arnaudbesnier** [comment]
Is this a feature request?
Because it obviously won't work.

What happens if you select several records to trigger the Smart Actions, `object` won't have sense has you would have several `objects`.

Anyway, I guess that what you want is dynamic default values (according to the selected record) for your Smart Action forms. Is that right?

**Comment by arnaudbesnier** [comment]
Hey @lucasgerard, we've recently released a feature that enables developers to pre-fill values (using the current record context) of Smart Action forms.

The documentation is available here: https://doc.forestadmin.com/developer-guide/rails.html#prefill-a-form-with-default-values

🌲🌲🌲
