### ISSUE TITLE
[*] Search - Escaping issues / Possible SQL injection on searches?

### ISSUE THREAD

**Issue by blakewest** [ForestAdmin/forest-rails#252]
## Expected behavior

I would expect that when passing in a string to search by, it would be properly escaped, and I would not get an error.

## Actual behavior

I see an error. Specifically, a syntax error when passing in a `'` to the search bar.

## Failure Logs
This image is from our Sentry logs of when this happened.
![image](https://user-images.githubusercontent.com/2524396/38272578-79ff0c5c-373e-11e8-9510-a37945a5752d.png)

Some other stuff from the stack trace:
![image](https://user-images.githubusercontent.com/2524396/38272738-f8a51254-373e-11e8-9be1-26576ffd07e9.png)

## Context
Our customer support admin was using forest and ran into this error. Is this possibly SQL injection?

* Package Version: 1.7.7
* Rails Version: 4.2
* Database Dialect: Postgres
* Database Version: 9.6

**Comment by Uelb** [comment]
@blakewest I think you are right, I dug in the code to understand what was happening as I got the same issue, and it seems like it's caused by this line : 
https://github.com/ForestAdmin/forest-rails/blob/devel/app/services/forest_liana/search_query_builder.rb#L76
As you can see, there is no escaping whatsoever.

**Comment by arnaudbesnier** [comment]
@blakewest , @Uelb this is fixed in the latest liana version (v2.11.4).

Thanks for the report!
🌲🌲🌲
