### ISSUE TITLE
How to create an editable association field

### ISSUE THREAD

**Issue by Uelb** [ForestAdmin/forest-rails#275]
## Expected behavior

I have an application where users have companies.
I want to create a smart action allowing me to attach several users to a company quickly, the standard association interface is not powerful enough for my case as I can only add users one by one to the specific company. I wanted to create a smart action on the user collection to do that but have been unsuccessful to do so. I read most of the documentation and find no such example. Is this possible ?

I tried : 
````ruby
    action 'Attach a company', fields: [{
      field: :company,
      type: 'Number',
      reference: 'companies.id',
      isRequired: true
    }]
````

## Actual behavior

The form of the action opens but I cannot select the company, the field is disabled. I don't understand how to specify that the user can select from another table.

## Context

* Package Version: 2.4.9
* Rails Version: 5.2.0
* Database Dialect: PostgresQL
* Database Version: 9.6.1

**Comment by arnaudbesnier** [comment]
Hi @Uelb , sorry for the very late response, I hope you managed to implement the Smart Action form in the end.

I tried this code:
```ruby
action 'Attach a company', fields: [{
      field: :company,
      type: 'Number',
      reference: 'companies.id',
      isRequired: true
    }]
```
and it does not work indeed.
The reason is most likely that you need to use the model name when you declare the `reference` value. And I guess:
```ruby
action 'Attach a company', fields: [{
      field: :company,
      type: 'Number',
      reference: 'Company.id',
      isRequired: true
    }]
```
will give better results.

Let me close the thread, but feel free to re-open it if the issue persists.
